### ISSUE TITLE
aws-load-balancer-security-groups label reset content of security group

### ISSUE THREAD

**Issue by albundy83** [outscale-dev/cloud-provider-osc#180]
Hello,

I use release `v0.2.0` and when I specify an already created security group like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  labels:
    app.kubernetes.io/name: kibana
  annotations:
    service.beta.kubernetes.io/osc-load-balancer-name: kibana-easi
    service.annotations.service.beta.kubernetes.io/osc-load-balancer-name-length: "20"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::xxxxxxxxxxxx:server-certificate/Cockpit/toto.fr"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-xxxxxxxx"
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5601
  type: LoadBalancer
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: easi
```
The content of my security group `sg-xxxxxxxx` is reset and come back to original state:
```
HTTPS	inbound		tcp		443	443	0.0.0.0/0
Custom	outbound	-1				0.0.0.0/0
ICMP	inbound		icmp	-1	-1	0.0.0.0/0
```
All my custom modifications are removed.
Is it normal behaviour ?

**Comment by outscale-mdr** [comment]
Hello @albundy83,

The plugin will ensure that the first security group has only these rules. What you can do for your purpose is to use `service.beta.kubernetes.io/aws-load-balancer-extra-security-groups` instead of `service.beta.kubernetes.io/aws-load-balancer-security-groups`.

**Comment by albundy83** [comment]
I understand but if the first security group allow inboud on 0.0.0.0/0, my extra security group will be useless no ?

**Comment by outscale-mdr** [comment]
Indeed, it depends on what you wanted to achieve with your security groups. Do you have an use case ?

**Comment by albundy83** [comment]
Yes sure, I simply want that when I create a Load Balancer in my cluster a security group with only some allowed IP is used.
I have 6 IP addresses that must be allowed that's all.
What I don't want is to have my Load Balancer accessed by every one from everywhere :)

**Comment by outscale-mdr** [comment]
Ok thank you !

In the service,spec  you could define `loadBalancerSourceRanges` ([doc](https://kubernetes.io/fr/docs/concepts/services-networking/service/#aws-nlb-support))

In your example:
```
apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  labels:
    app.kubernetes.io/name: kibana
  annotations:
    service.beta.kubernetes.io/osc-load-balancer-name: kibana-easi
    service.annotations.service.beta.kubernetes.io/osc-load-balancer-name-length: "20"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::xxxxxxxxxxxx:server-certificate/Cockpit/toto.fr"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-xxxxxxxx"
spec:
  loadBalancerSourceRanges:
    - FIRST_IP_RANGE
    - SECOND_IP_RANGE
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5601
  type: LoadBalancer
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: easi
```

Could this work for you ?
